version: "3.9"

services:

  backend:
    build: ./server
    container_name: taskflow-backend

    ports:
      - "5001:5001"

    env_file:
      - ./server/.env

    restart: always

  frontend:
    build: ./client
    container_name: taskflow-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    restart: always
