services:
  backend:
    build: ./server
    container_name: taskflow-backend

    ports:
      - "5001:5001"

    env_file:
      - ./server/.env

    restart: always

  frontend:
    build: ./client
    container_name: taskflow-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    restart: always

  nginx:
    image: nginx:latest
    container_name: taskflow-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
      - backend

    restart: always