pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/shubhammkbd17/taskflow.git'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Run Containers') {
            steps {
                sh 'docker compose up -d'
            }
        }

        stage('Test') {
            steps {
                sh 'docker ps'
            }
        }
    }
}